### ISSUE TITLE
✨ [Feat] CRUD 중 Update 기능 구현

### ISSUE THREAD

**Issue by jinho7** [SMUMC-6th/6th_SPRING#113]
## 📝 개요
- CRUD 중 Update 기능 구현

## ✔️ To-Do
- [x] #86 Refactoring
- [x] CRUD 중 Update 기능 구현
- [x] 연관 관계 편의 메소드
- [x] JPA 쿼리 메소드

## 👀 ETC
-
