### ISSUE TITLE
✨ [Feat] CRUD 중 Update 기능 구현

### ISSUE THREAD

**Issue by 202111255** [SMUMC-6th/6th_SPRING#114]
## 📝 개요
- 저번주 코드 Refactoring 하기
- CRUD 중 Update 기능 구현
- 연관관계와 JPA Query Method

## ✔️ To-Do
- [ ] 삭제응답 통일
- [ ] url 공통부분 통일
- [ ] CRUD 중 Update 기능 구현
- [ ] user - post 연관관계 이어주기
- [ ] user, post - reply 연관관계 이어주기
- [ ] JPA Query Method를 이용하여 userId로 post 조회하기
- [ ] JPA Query Method를 이용하여 userId, postId로 reply 조회하기
- [ ] CORS 에러해결

## 👀 ETC
- 참고자료 등 기타 내용 작성
