### ISSUE TITLE
✨ [Feat] CRUD 중 Update 기능 구현

### ISSUE THREAD

**Issue by HyunwooYi** [SMUMC-6th/6th_SPRING#129]
## 📝 개요
- CRUD 중 Update 기능 구현
- 연관 관계 편의 메소드
- JPA 쿼리 메소드
- CORS 에러 해결

## ✔️ To-Do
- [x] CRUD 중 Update 기능 구현
- [x] 연관 관계 편의 메소드
- [x] JPA 쿼리 메소드
- [x] CORS 에러 해결

## 👀 ETC
- 참고자료 등 기타 내용 작성
